# Generated by Django 4.2.19 on 2025-02-15 15:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_dutyschedule_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationrequest',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='middle_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='position',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='rank',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userchangerequest',
            name='requested_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
