from django.urls import path
from . import views

urlpatterns = [
    path('', views.home_view, name='home'),
    path('login/', views.login_view, name='login'),
    path('register/', views.register_view, name='register'),
    path('admin-dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('approve-requests/', views.approve_registration_requests, name='approve_requests'),
    path('user-dashboard/', views.user_dashboard, name='user_dashboard'),
    path('get-duties-json/', views.get_duties_json, name='get_duties_json'),
    path('analytics/', views.analytics_view, name='analytics'),
    path('user-analytics/', views.user_analytics_view, name='user_analytics'),
    path('chat/<int:receiver_id>/', views.chat_view, name='chat'),
    path('logout/', views.CustomLogoutView.as_view(), name='logout'),
    path('assign-duty/', views.assign_duty, name='assign_duty'),
    path('save-duties/', views.save_duties, name='save_duties'),
    path('get-duties/', views.get_duties, name='get_duties'),
    path('users-list/', views.users_list, name='users_list'),
    path('edit-user/<int:user_id>/', views.edit_user, name='edit_user'),
    path('delete-user/<int:user_id>/', views.delete_user, name='delete_user'),
    path('get-user-data/<int:user_id>/', views.get_user_data, name='get_user_data'),
    path('get-user-duties-by-month/', views.get_user_duties_by_month, name='get_user_duties_by_month'),
    path('admin-analytics/', views.admin_analytics_view, name='admin_analytics'),
    path('export-duty-schedule/', views.export_duty_schedule, name='export_duty_schedule'),
    path('chat-list/', views.chat_list, name='chat_list'),
    path('chat-with-admin/', views.chat_with_admin, name='chat_with_admin'),
    path('workday/', views.workday_view, name='workday'),
    path('workday/toggle-task/<int:task_id>/', views.toggle_task, name='toggle_task'),
    path('mark_notification_as_read/<int:notification_id>/', views.mark_notification_as_read, name='mark_notification_as_read'),
    path('delete-notification/<int:notification_id>/', views.delete_notification, name='delete_notification'),
    path('update-profile/', views.update_profile, name='update_profile'),
    path('export-attendance/', views.export_attendance, name='export_attendance'),
]